### ISSUE TITLE
can i use it to reduce asset size in Unity game ?

### ISSUE THREAD

**Issue by wangjianpeng** [MiloszKrajewski/lz4net#24]
I have some game assets to compress, when i use the unity method to compress them by lzma, the ultimate size is 44M, when i use unity method to compress them with lz4, it is 56M.
As compare i use the lz4net with encoder hc to compress them , the final size is 66M,   can i use this library to make better compress in Unity ?

**Comment by lostromb** [comment]
It depends what you mean by "better compress". If you mean "smaller", then no, LZ4 is not the best. But I'm assuming since you're in Unity you're dealing with real-time game scenarios, either you're streaming content during play or you have load screens where you want to keep the time down. In that case I think LZ4 is a great option. It has low latency, high throughput, and decent compression ratios depending on the content.

One note is that although LZ4 does an OK job with general-purpose content (Scripts, vertex, animation and mesh data probably compress well) it is not the best suited for all types of game assets such as audio samples or textures. For example, the Opus codec will easily compress audio to 5% original size which can be crucial if your game uses lots of dialog or music. So it all depends on your exact situation and how you're willing to trade off compression size vs. speed

**Comment by MiloszKrajewski** [comment]
It's a little bit suprising. In general - "no" - if you already use lz4net HC codec, you won't be able to do any better. A lot of waste may be introduced when you compress every file separately (I don't know what Unity does). You can also try adjust blocksize when compressing streams.
