### ISSUE TITLE
Cannot build as .net native, cannot submit to store

### ISSUE THREAD

**Issue by JarrydSemmens** [MiloszKrajewski/lz4net#30]
When compiling v1.0.15.93 as a .net native, the following error is thrown:

`ILT0042: Arrays of pointer types are not currently supported: 'System.Byte*[]'.__`

This means, that UWP store applications cannot contain lz4net, which blocked the submission of my app when using lz4net.

Here's a stackoverflow about it.
https://stackoverflow.com/questions/47852677/how-do-i-solve-net-native-compilation-error-ilt0042-for-uwp-app/47853011#47853011

**Comment by MiloszKrajewski** [comment]
FYI: I'm in the process of porting 1.8.1 to .NET Standard. It wont support .NET < 4.6 and will be "Unsafe" only. For now, there are some performance problems, as inline functions in .NET don't work the same way as in C (not everything gets inlined as I would like it to be). 
Due to braking changes it will be released as different nuget package. You can monitor development here: https://github.com/MiloszKrajewski/K4os.Compression.LZ4 (empty at the time of writing)

**Comment by MiloszKrajewski** [comment]
https://github.com/MiloszKrajewski/K4os.Compression.LZ4
