### ISSUE TITLE
.Net Standard Support and Compatible Streaming Support

### ISSUE THREAD

**Issue by kraptor23** [MiloszKrajewski/lz4net#31]
I created a fork at https://github.com/TaniusTech/Lz4 which focuses on .Net Standard 2.0 support for windows/linux, and am looking for lz4 native streaming support. Let me know if you have any guidance on this, as either I or a freelancer will tackle adding a C# stream to make this easier.

**Comment by MiloszKrajewski** [comment]
So it seems we will be duplicating some work.
I'm actually working on new (.NET Standard 1.0) implementation with compatible streaming implementation. New implementation will not support .NET 2 (so I guess Unity is out for a while) nor Safe mode, but will work with all .NET Standard 1.0 compatible stacks: .NET Core 1.1+ and .NET Framework 4.6+.

**Comment by kraptor23** [comment]
That sounds ideal - glad to hear it! I hired someone to also make a port which I will push up - I'll respond once they have done a pass at it.

**Comment by kraptor23** [comment]
So as we've dug in - we implemented the streaming format, but realized that the LZ4 codec is from 2013 before the linked blocks feature was added. How are things going on your port of later version + streaming compatibility?

**Comment by MiloszKrajewski** [comment]
FYI: I'm in the process of porting 1.8.1 to .NET Standard. It wont support .NET < 4.6 and will be "Unsafe" only. For now, there are some performance problems, as inline functions in .NET don't work the same way as in C (not everything gets inlined as I would like it to be). 
Due to braking changes it will be released as different nuget package. You can monitor development here: https://github.com/MiloszKrajewski/K4os.Compression.LZ4 (empty at the time of writing)

**Comment by kraptor23** [comment]
Thanks Milos - I'll keep a close eye on the repo - looking forward to the new build!

-Karl

**Comment by MiloszKrajewski** [comment]
https://github.com/MiloszKrajewski/lz4net/blob/master/doc/compatibility.md

**Comment by MiloszKrajewski** [comment]
See: https://github.com/MiloszKrajewski/K4os.Compression.LZ4
